version: '3.7'

services:
  eurekaserver:
    image: ostock/eurekaserver:0.0.1-SNAPSHOT
    ports:
      - "8070:8070"
    
    networks:
      backend:
        aliases:
          - "eurekaserver"
networks:
  backend:
    driver: bridge